plugins {
	id 'java-library'
	id 'org.springframework.boot'
}

dependencies {
	implementation project(':obelix-common')
	implementation project(':obelix-quarry-api')
	implementation 'org.springframework.boot:spring-boot-starter-webclient'
	implementation 'org.springframework.boot:spring-boot-starter-aspectj'

	testImplementation testFixtures(project(':obelix-common'))
}

tasks.named("bootBuildImage") {
	imageName = "bbw/obelix-webshop:latest"
}
