global:
  scrape_interval: 5s

scrape_configs:
  - job_name: quarry
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]
  - job_name: webshop
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
