spring:
  datasource:
    url: jdbc:h2:mem:obelixdb
  jpa:
    open-in-view: on
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: http://localhost:9411/api/v2/spans
  observations:
    annotations:
      enabled: true
