plugins {
	id 'java-library'
	id 'java-test-fixtures'
}

dependencies {
	api 'org.springframework.boot:spring-boot-starter-actuator'
	api 'org.springframework.boot:spring-boot-starter-data-jpa'
	api 'org.springframework.boot:spring-boot-starter-validation'
	api 'org.springframework.boot:spring-boot-starter-web'

	implementation 'org.springframework.boot:spring-boot-micrometer-tracing-opentelemetry'
	implementation 'org.springframework.boot:spring-boot-zipkin'
	implementation 'io.micrometer:micrometer-tracing-bridge-otel'
	implementation 'io.opentelemetry:opentelemetry-exporter-zipkin'

	runtimeOnly 'io.micrometer:micrometer-registry-prometheus'
	runtimeOnly 'com.h2database:h2' // for now...

	testFixturesApi 'org.springframework.boot:spring-boot-starter-test'
	testFixturesApi 'org.springframework.boot:spring-boot-starter-webflux'
	testFixturesApi 'org.springframework.boot:spring-boot-webtestclient'
	testFixturesApi 'org.assertj:assertj-core'
	testFixturesRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
